name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.8.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set TAG from push or input
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF##*/}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Extract changelog for version
        id: changelog
        shell: bash
        run: |
          ver="${{ steps.vars.outputs.version }}"
          if [ -f CHANGELOG.md ]; then
            awk -v ver="## "ver'$' '
              found{ if ($0 ~ /^## / && $0 !~ ver) exit; print }
              $0 ~ ver { found=1; print }
            ' CHANGELOG.md > RELEASE_NOTES.md || true
          fi
          echo "notes_file=RELEASE_NOTES.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: EquiFastJoin ${{ steps.vars.outputs.version }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

